import type { GitaVerse } from "./types";

/**
 * GITA: one Bhagavad Gita verse a day.
 *
 * Sanskrit follows the standard Gita Press / critical recension (half-verses on separate lines,
 * verse marker ॥अध्याय-श्लोक॥ in Devanagari numerals). IAST mirrors the Devanagari word division,
 * with anusvara written ṃ and avagraha written as an apostrophe. Speaker headings such as
 * "śrībhagavānuvāca" are not part of the verse text and are omitted.
 *
 * Tone (blueprint): guidance without fear; the reader keeps their agency; devotional practice
 * is offered as devotion, never as a substitute for medical or mental-health care.
 */

export const GITA_CHAPTERS: Record<number, string> = {
  1: "Arjuna Vishada Yoga",
  2: "Sankhya Yoga",
  3: "Karma Yoga",
  4: "Jnana Karma Sannyasa Yoga",
  5: "Karma Sannyasa Yoga",
  6: "Dhyana Yoga",
  7: "Jnana Vijnana Yoga",
  8: "Akshara Brahma Yoga",
  9: "Raja Vidya Raja Guhya Yoga",
  10: "Vibhuti Yoga",
  11: "Vishvarupa Darshana Yoga",
  12: "Bhakti Yoga",
  13: "Kshetra Kshetrajna Vibhaga Yoga",
  14: "Gunatraya Vibhaga Yoga",
  15: "Purushottama Yoga",
  16: "Daivasura Sampad Vibhaga Yoga",
  17: "Shraddhatraya Vibhaga Yoga",
  18: "Moksha Sannyasa Yoga",
};

export const GITA: GitaVerse[] = [
  {
    id: "2.14",
    chapter: 2,
    verse: 14,
    chapterName: "Sankhya Yoga",
    sanskrit: "मात्रास्पर्शास्तु कौन्तेय शीतोष्णसुखदुःखदाः ।\nआगमापायिनोऽनित्यास्तांस्तितिक्षस्व भारत ॥२-१४॥",
    transliteration: "mātrāsparśāstu kaunteya śītoṣṇasukhaduḥkhadāḥ\nāgamāpāyino'nityāstāṃstitikṣasva bhārata",
    meaning: "O son of Kunti, the contact of the senses with their objects gives rise to cold and heat, pleasure and pain. They come and go; they do not last. Bear them patiently, O Bharata.",
    lesson: "Moods, comforts and discomforts arrive and leave like the seasons. Titiksha (patient endurance) is not pretending you feel nothing; it is refusing to let a passing state make your decisions for you. When a hard feeling comes, you can name it, breathe, and keep choosing well. If pain stays heavy for a long time, reaching out for care and support is part of the same wisdom.",
    reflection: "Which passing feeling has been making decisions for you lately?",
    action: "The next time discomfort or irritation rises today, pause for three slow breaths and quietly tell yourself, \"This comes and goes.\"",
    themes: ["fear", "discipline"],
  },
  {
    id: "2.20",
    chapter: 2,
    verse: 20,
    chapterName: "Sankhya Yoga",
    sanskrit: "न जायते म्रियते वा कदाचिन्नायं भूत्वा भविता वा न भूयः ।\nअजो नित्यः शाश्वतोऽयं पुराणो न हन्यते हन्यमाने शरीरे ॥२-२०॥",
    transliteration: "na jāyate mriyate vā kadācinnāyaṃ bhūtvā bhavitā vā na bhūyaḥ\najo nityaḥ śāśvato'yaṃ purāṇo na hanyate hanyamāne śarīre",
    meaning: "The Self is never born, nor does it ever die. It did not come into being, nor will it ever cease to be. Unborn, eternal, everlasting and ancient, it is not slain when the body is slain.",
    lesson: "Beneath your roles, results and reputation is something no loss can touch. Remembering this does not make grief or change unimportant; it gives you a steady place to stand while you go through them. You are more than what happens to you.",
    reflection: "If you are not only your body, your job or your reputation, which part of you deserves more of your attention?",
    action: "Sit quietly for two minutes today and simply notice the one who is aware of your breath, the sounds around you and your thoughts, without trying to change anything.",
    themes: ["fear", "ego"],
  },
  {
    id: "2.38",
    chapter: 2,
    verse: 38,
    chapterName: "Sankhya Yoga",
    sanskrit: "सुखदुःखे समे कृत्वा लाभालाभौ जयाजयौ ।\nततो युद्धाय युज्यस्व नैवं पापमवाप्स्यसि ॥२-३८॥",
    transliteration: "sukhaduḥkhe same kṛtvā lābhālābhau jayājayau\ntato yuddhāya yujyasva naivaṃ pāpamavāpsyasi",
    meaning: "Treating alike pleasure and pain, gain and loss, victory and defeat, prepare yourself for battle. Fighting in this way, you will incur no sin.",
    lesson: "Arjuna's battle was his rightful duty as a warrior; ours is usually the work, study or responsibility in front of us. Krishna's advice is to step into it with an even mind, not chasing the win or dreading the loss, but doing what is right because it is right. Steadiness, not the outcome, keeps the heart clean.",
    reflection: "Would you act differently today if winning and losing mattered less than doing the right thing?",
    action: "Before one important task today, tell yourself, \"Gain or loss, I will do this well and honestly,\" and then begin.",
    themes: ["success-and-failure", "duty"],
  },
  {
    id: "2.47",
    chapter: 2,
    verse: 47,
    chapterName: "Sankhya Yoga",
    sanskrit: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन ।\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि ॥२-४७॥",
    transliteration: "karmaṇyevādhikāraste mā phaleṣu kadācana\nmā karmaphalaheturbhūrmā te saṅgo'stvakarmaṇi",
    meaning: "Your right is to action alone, never to its fruits. Do not let the fruits of action be your motive, and do not be attached to inaction either.",
    lesson: "You control your effort, your honesty and your attention, not the final result. Letting go of the fruit is not carelessness; it frees you to give your best without anxiety. And the verse closes the easy exit too: detachment never means giving up on action.",
    reflection: "Where are you so focused on the result that you have stopped caring about the work itself?",
    action: "Choose one task today and give it 25 minutes of full attention without checking how it will be judged.",
    themes: ["duty", "success-and-failure"],
  },
  {
    id: "2.48",
    chapter: 2,
    verse: 48,
    chapterName: "Sankhya Yoga",
    sanskrit: "योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय ।\nसिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते ॥२-४८॥",
    transliteration: "yogasthaḥ kuru karmāṇi saṅgaṃ tyaktvā dhanañjaya\nsiddhyasiddhyoḥ samo bhūtvā samatvaṃ yoga ucyate",
    meaning: "Established in yoga, perform your actions, O Dhananjaya, giving up attachment and remaining the same in success and failure. This evenness of mind is called yoga.",
    lesson: "Yoga here is not a posture but a state of mind: samatva, balance. Success and failure will both visit; the yogi meets them with the same steady heart. That steadiness makes your work cleaner and your relationships kinder.",
    reflection: "How do you usually react to success and to failure, and what would an even response to both look like?",
    action: "Today, whether something goes well or badly, answer it with the same calm sentence: \"Noted. What is the next right step?\"",
    themes: ["success-and-failure", "discipline"],
  },
  {
    id: "2.50",
    chapter: 2,
    verse: 50,
    chapterName: "Sankhya Yoga",
    sanskrit: "बुद्धियुक्तो जहातीह उभे सुकृतदुष्कृते ।\nतस्माद्योगाय युज्यस्व योगः कर्मसु कौशलम् ॥२-५०॥",
    transliteration: "buddhiyukto jahātīha ubhe sukṛtaduṣkṛte\ntasmādyogāya yujyasva yogaḥ karmasu kauśalam",
    meaning: "One endowed with this wisdom casts off, here in this very life, both good and bad deeds. Therefore devote yourself to yoga; yoga is skill in action.",
    lesson: "Skill in action means doing your work so wisely and cleanly that it does not bind you: no hidden agenda, no anxious grasping. A craftsperson absorbed in the craft, a nurse giving full care, a parent listening patiently are all practising yoga in daily life. Excellence and inner freedom can grow together.",
    reflection: "Which ordinary task in your day could become an act of yoga if you did it with full care?",
    action: "Choose one routine task today, such as cooking, an email or a small repair, and do it with complete attention, as an offering.",
    themes: ["discipline", "duty"],
  },
  {
    id: "2.56",
    chapter: 2,
    verse: 56,
    chapterName: "Sankhya Yoga",
    sanskrit: "दुःखेष्वनुद्विग्नमनाः सुखेषु विगतस्पृहः ।\nवीतरागभयक्रोधः स्थितधीर्मुनिरुच्यते ॥२-५६॥",
    transliteration: "duḥkheṣvanudvignamanāḥ sukheṣu vigataspṛhaḥ\nvītarāgabhayakrodhaḥ sthitadhīrmunirucyate",
    meaning: "One whose mind is not shaken in sorrow, who has no craving for pleasures, and who is free from attachment, fear and anger, is called a sage of steady wisdom.",
    lesson: "A person of steady wisdom (sthita-dhi) still feels; they are simply not thrown about by every feeling. As attachment loosens, fear and anger lose their grip. This steadiness is built slowly, one calm response at a time.",
    reflection: "Which of the three, attachment, fear or anger, most often unsettles your mind?",
    action: "When you notice anger or fear rising today, wait one full minute before you speak or act.",
    themes: ["anger", "fear", "desire"],
  },
  {
    id: "2.62",
    chapter: 2,
    verse: 62,
    chapterName: "Sankhya Yoga",
    sanskrit: "ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते ।\nसङ्गात्सञ्जायते कामः कामात्क्रोधोऽभिजायते ॥२-६२॥",
    transliteration: "dhyāyato viṣayānpuṃsaḥ saṅgasteṣūpajāyate\nsaṅgātsañjāyate kāmaḥ kāmātkrodho'bhijāyate",
    meaning: "When a person dwells on the objects of the senses, attachment to them arises. From attachment, desire is born, and from desire, anger arises.",
    lesson: "Krishna maps how inner trouble begins: not with one big decision, but with repeatedly dwelling on something. What we dwell on grows. The good news is that the chain is easiest to break at its very first link, by choosing where to rest your attention.",
    reflection: "What have you been dwelling on lately, and is it feeding your peace or your restlessness?",
    action: "Notice one craving or recurring thought today and gently turn your attention to something useful or uplifting for five minutes.",
    themes: ["desire", "anger"],
  },
  {
    id: "2.63",
    chapter: 2,
    verse: 63,
    chapterName: "Sankhya Yoga",
    sanskrit: "क्रोधाद्भवति सम्मोहः सम्मोहात्स्मृतिविभ्रमः ।\nस्मृतिभ्रंशाद्बुद्धिनाशो बुद्धिनाशात्प्रणश्यति ॥२-६३॥",
    transliteration: "krodhādbhavati sammohaḥ sammohātsmṛtivibhramaḥ\nsmṛtibhraṃśādbuddhināśo buddhināśātpraṇaśyati",
    meaning: "From anger comes delusion; from delusion, confusion of memory; from the loss of memory, the ruin of discernment; and when discernment is ruined, a person is lost.",
    lesson: "Anger clouds judgement: in its grip we forget what we value and say things we would never choose to say. Seeing this chain clearly is empowering, because every link is a place where you can pause. Protecting your discernment is a daily act of self-respect.",
    reflection: "The last time you acted in anger, what did you forget in that moment?",
    action: "Write down one phrase you will use to pause when anger rises, such as \"Let me come back to this in ten minutes,\" and use it today if you need it.",
    themes: ["anger", "discipline"],
  },
  {
    id: "2.70",
    chapter: 2,
    verse: 70,
    chapterName: "Sankhya Yoga",
    sanskrit: "आपूर्यमाणमचलप्रतिष्ठं समुद्रमापः प्रविशन्ति यद्वत् ।\nतद्वत्कामा यं प्रविशन्ति सर्वे स शान्तिमाप्नोति न कामकामी ॥२-७०॥",
    transliteration: "āpūryamāṇamacalapratiṣṭhaṃ samudramāpaḥ praviśanti yadvat\ntadvatkāmā yaṃ praviśanti sarve sa śāntimāpnoti na kāmakāmī",
    meaning: "As waters enter the ocean, which is ever being filled yet stays steady and unmoved, so the one into whom all desires enter in the same way attains peace, not the one who chases desires.",
    lesson: "Desires will keep arriving, like rivers reaching the sea. Peace does not come from fulfilling every one of them, but from being deep enough that they do not overflow you. You can notice a want, let it pass through, and remain yourself.",
    reflection: "Which desire, if you stopped chasing it, would give you more peace than getting it?",
    action: "When a want arises today, whether a purchase, a snack or another scroll, notice it, let it sit for ten minutes, and then decide calmly.",
    themes: ["desire", "comparison"],
  },
  {
    id: "3.8",
    chapter: 3,
    verse: 8,
    chapterName: "Karma Yoga",
    sanskrit: "नियतं कुरु कर्म त्वं कर्म ज्यायो ह्यकर्मणः ।\nशरीरयात्रापि च ते न प्रसिद्ध्येदकर्मणः ॥३-८॥",
    transliteration: "niyataṃ kuru karma tvaṃ karma jyāyo hyakarmaṇaḥ\nśarīrayātrāpi ca te na prasiddhyedakarmaṇaḥ",
    meaning: "Perform your prescribed duty, for action is better than inaction. Without action, even the maintenance of your body would not be possible.",
    lesson: "Spiritual life is not an escape from work. Doing your share at home, at work and in your community is itself a sacred discipline. Even small duties done faithfully keep life moving, for you and for others.",
    reflection: "Is there a duty you have been postponing while waiting for the perfect moment?",
    action: "Finish one small duty you have been putting off, today, before evening.",
    themes: ["duty", "discipline"],
  },
  {
    id: "3.19",
    chapter: 3,
    verse: 19,
    chapterName: "Karma Yoga",
    sanskrit: "तस्मादसक्तः सततं कार्यं कर्म समाचर ।\nअसक्तो ह्याचरन्कर्म परमाप्नोति पूरुषः ॥३-१९॥",
    transliteration: "tasmādasaktaḥ satataṃ kāryaṃ karma samācara\nasakto hyācarankarma paramāpnoti pūruṣaḥ",
    meaning: "Therefore, without attachment, always perform the work that has to be done; for by doing work without attachment, a person attains the Supreme.",
    lesson: "Work done without clinging becomes a spiritual path in itself. You still care about doing it well; you simply stop making your peace depend on applause or reward. Everyday duties then become quiet practice.",
    reflection: "Which of your responsibilities could you carry more lightly if you expected nothing back?",
    action: "Do one helpful thing today without mentioning it to anyone.",
    themes: ["duty", "service"],
  },
  {
    id: "3.21",
    chapter: 3,
    verse: 21,
    chapterName: "Karma Yoga",
    sanskrit: "यद्यदाचरति श्रेष्ठस्तत्तदेवेतरो जनः ।\nस यत्प्रमाणं कुरुते लोकस्तदनुवर्तते ॥३-२१॥",
    transliteration: "yadyadācarati śreṣṭhastattadevetaro janaḥ\nsa yatpramāṇaṃ kurute lokastadanuvartate",
    meaning: "Whatever a great person does, others follow. Whatever standard such a person sets, the world follows.",
    lesson: "Everyone leads someone: a child, a colleague, a friend who is quietly watching. People copy what we do far more than what we say. Living your values visibly is the most powerful teaching there is.",
    reflection: "Who is watching how you live, and what are they learning from you?",
    action: "Model one habit today that you wish others around you would adopt, such as punctuality, kind speech or tidiness, without commenting on it.",
    themes: ["leadership"],
  },
  {
    id: "3.27",
    chapter: 3,
    verse: 27,
    chapterName: "Karma Yoga",
    sanskrit: "प्रकृतेः क्रियमाणानि गुणैः कर्माणि सर्वशः ।\nअहङ्कारविमूढात्मा कर्ताहमिति मन्यते ॥३-२७॥",
    transliteration: "prakṛteḥ kriyamāṇāni guṇaiḥ karmāṇi sarvaśaḥ\nahaṅkāravimūḍhātmā kartāhamiti manyate",
    meaning: "All actions are performed in every way by the gunas, the qualities of material nature (prakriti). But one whose mind is deluded by ego thinks, \"I am the doer.\"",
    lesson: "So much has to come together for anything to happen: body, circumstances, timing and the work of countless others. The ego claims all the credit and all the blame, and both are heavy to carry. Seeing the bigger picture brings humility in success and gentleness with yourself in failure.",
    reflection: "Where are you carrying credit or blame that does not belong to you alone?",
    action: "Today, thank three people or circumstances that made one of your recent achievements possible.",
    themes: ["ego", "gratitude"],
  },
  {
    id: "3.35",
    chapter: 3,
    verse: 35,
    chapterName: "Karma Yoga",
    sanskrit: "श्रेयान्स्वधर्मो विगुणः परधर्मात्स्वनुष्ठितात् ।\nस्वधर्मे निधनं श्रेयः परधर्मो भयावहः ॥३-३५॥",
    transliteration: "śreyānsvadharmo viguṇaḥ paradharmātsvanuṣṭhitāt\nsvadharme nidhanaṃ śreyaḥ paradharmo bhayāvahaḥ",
    meaning: "Better is one's own dharma, though imperfectly performed, than the dharma of another well performed. Better is death in one's own dharma; the dharma of another is fraught with fear.",
    lesson: "Svadharma is your own path: the duties and gifts that truly belong to you. Copying someone else's life, however impressive it looks, brings constant insecurity. Krishna's strong phrase about death in one's own dharma is a vivid way of stressing commitment, not a call to danger: walking your own way imperfectly is better than performing someone else's perfectly.",
    reflection: "Where are you measuring your life against someone else's path instead of your own?",
    action: "Write down one strength or responsibility that is truly yours, and spend twenty minutes on it today instead of comparing yourself with others.",
    themes: ["comparison", "duty", "fear"],
  },
  {
    id: "4.7",
    chapter: 4,
    verse: 7,
    chapterName: "Jnana Karma Sannyasa Yoga",
    sanskrit: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत ।\nअभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम् ॥४-७॥",
    transliteration: "yadā yadā hi dharmasya glānirbhavati bhārata\nabhyutthānamadharmasya tadātmānaṃ sṛjāmyaham",
    meaning: "Whenever there is a decline of dharma (righteousness) and a rise of adharma (unrighteousness), O Bharata, then I manifest Myself.",
    lesson: "This is a verse of hope: goodness is never abandoned, and the Divine responds when the world loses its balance. Devotees draw courage from it instead of despairing at the news of the day. We can also become small instruments of that restoration through honest, kind and brave choices.",
    reflection: "Where in your own corner of the world could you help restore a little balance?",
    action: "Do one quiet act today that adds goodness where it is missing: a fair word, a kept promise, or help for someone overlooked.",
    themes: ["service", "duty"],
  },
  {
    id: "4.38",
    chapter: 4,
    verse: 38,
    chapterName: "Jnana Karma Sannyasa Yoga",
    sanskrit: "न हि ज्ञानेन सदृशं पवित्रमिह विद्यते ।\nतत्स्वयं योगसंसिद्धः कालेनात्मनि विन्दति ॥४-३८॥",
    transliteration: "na hi jñānena sadṛśaṃ pavitramiha vidyate\ntatsvayaṃ yogasaṃsiddhaḥ kālenātmani vindati",
    meaning: "Truly, there is nothing in this world as purifying as knowledge. One who is perfected in yoga finds it within oneself in due course of time.",
    lesson: "Jnana, true knowledge, cleanses the mind like nothing else because it changes how we see. It is not gathered all at once; it ripens through patient practice. Keep showing up, and understanding will dawn from within.",
    reflection: "What practice are you willing to keep up patiently, even before you see results?",
    action: "Read one verse or one page of a wisdom text slowly today, and note down a line you want to remember.",
    themes: ["discipline"],
  },
  {
    id: "5.10",
    chapter: 5,
    verse: 10,
    chapterName: "Karma Sannyasa Yoga",
    sanskrit: "ब्रह्मण्याधाय कर्माणि सङ्गं त्यक्त्वा करोति यः ।\nलिप्यते न स पापेन पद्मपत्रमिवाम्भसा ॥५-१०॥",
    transliteration: "brahmaṇyādhāya karmāṇi saṅgaṃ tyaktvā karoti yaḥ\nlipyate na sa pāpena padmapatramivāmbhasā",
    meaning: "One who performs actions offering them to Brahman (the Divine), giving up attachment, is not touched by sin, just as a lotus leaf is not wetted by water.",
    lesson: "The lotus grows in water yet stays dry. In the same way, you can live fully in the world, with work, family, money and responsibility, without being stained by it, when you offer your actions to something higher. Offering changes the spirit of the work.",
    reflection: "What would change in your work if you thought of it as an offering?",
    action: "Before starting your main task today, silently dedicate it: \"May this work be an offering.\"",
    themes: ["service", "duty"],
  },
  {
    id: "5.18",
    chapter: 5,
    verse: 18,
    chapterName: "Karma Sannyasa Yoga",
    sanskrit: "विद्याविनयसम्पन्ने ब्राह्मणे गवि हस्तिनि ।\nशुनि चैव श्वपाके च पण्डिताः समदर्शिनः ॥५-१८॥",
    transliteration: "vidyāvinayasampanne brāhmaṇe gavi hastini\nśuni caiva śvapāke ca paṇḍitāḥ samadarśinaḥ",
    meaning: "The wise see with an equal eye a learned and humble brahmana (priest-scholar), a cow, an elephant, a dog and an outcaste (shvapaka, one whom society shut out).",
    lesson: "The wise look past learning, status, species and social rank to the same divine presence in all. This verse quietly challenges every hierarchy we use to judge others. Dignity is not earned by position; it is already present in every being.",
    reflection: "Whom do you treat differently because of their status, and how would equal vision change that?",
    action: "Today, offer the same warmth and respect to someone often overlooked, such as a cleaner, a driver or a street animal, as you would to someone important.",
    themes: ["relationships", "ego", "comparison"],
  },
  {
    id: "6.5",
    chapter: 6,
    verse: 5,
    chapterName: "Dhyana Yoga",
    sanskrit: "उद्धरेदात्मनात्मानं नात्मानमवसादयेत् ।\nआत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः ॥६-५॥",
    transliteration: "uddharedātmanātmānaṃ nātmānamavasādayet\nātmaiva hyātmano bandhurātmaiva ripurātmanaḥ",
    meaning: "Let a person lift oneself up by one's own self, and not let oneself sink down. For the self alone is one's friend, and the self alone is one's enemy.",
    lesson: "This is one of the Gita's most empowering teachings: your own mind can be your best friend or your harshest critic. You have the power to lift yourself, step by step, and reaching out to people you trust, or to a doctor or counsellor when you need it, is part of that lifting. Speak to yourself as a wise friend would: firmly, kindly and with belief.",
    reflection: "Is your inner voice behaving more like a friend or an enemy today?",
    action: "Write one encouraging sentence to yourself, as you would to a dear friend, and read it twice today.",
    themes: ["discipline", "success-and-failure"],
  },
  {
    id: "6.17",
    chapter: 6,
    verse: 17,
    chapterName: "Dhyana Yoga",
    sanskrit: "युक्ताहारविहारस्य युक्तचेष्टस्य कर्मसु ।\nयुक्तस्वप्नावबोधस्य योगो भवति दुःखहा ॥६-१७॥",
    transliteration: "yuktāhāravihārasya yuktaceṣṭasya karmasu\nyuktasvapnāvabodhasya yogo bhavati duḥkhahā",
    meaning: "For one who is moderate in eating and recreation, balanced in effort at work, and regulated in sleep and waking, yoga becomes the destroyer of sorrow.",
    lesson: "The Gita's path is not one of extremes: not starving or indulging, not overworking or idling. Balance in food, rest, play and effort is itself spiritual practice. A steady daily rhythm makes a calm mind far more possible.",
    reflection: "Which part of your daily rhythm, food, sleep, work or recreation, is most out of balance?",
    action: "Make one gentle adjustment today, such as a fixed bedtime or a simple sattvic (light and wholesome) meal eaten without screens.",
    themes: ["discipline"],
  },
  {
    id: "6.26",
    chapter: 6,
    verse: 26,
    chapterName: "Dhyana Yoga",
    sanskrit: "यतो यतो निश्चरति मनश्चञ्चलमस्थिरम् ।\nततस्ततो नियम्यैतदात्मन्येव वशं नयेत् ॥६-२६॥",
    transliteration: "yato yato niścarati manaścañcalamasthiram\ntatastato niyamyaitadātmanyeva vaśaṃ nayet",
    meaning: "Wherever the restless and unsteady mind wanders, one should restrain it from there and bring it back under the control of the Self alone.",
    lesson: "Krishna does not expect the mind to stop wandering; he asks us to keep bringing it back. Every return is the practice, not a failure. Over time, gentle repetition turns the mind into an ally.",
    reflection: "Can you bring your mind back without scolding yourself for wandering?",
    action: "Sit for five minutes with your attention on your breath or on a divine name; each time the mind wanders, kindly bring it back.",
    themes: ["discipline"],
  },
  {
    id: "6.32",
    chapter: 6,
    verse: 32,
    chapterName: "Dhyana Yoga",
    sanskrit: "आत्मौपम्येन सर्वत्र समं पश्यति योऽर्जुन ।\nसुखं वा यदि वा दुःखं स योगी परमो मतः ॥६-३२॥",
    transliteration: "ātmaupamyena sarvatra samaṃ paśyati yo'rjuna\nsukhaṃ vā yadi vā duḥkhaṃ sa yogī paramo mataḥ",
    meaning: "O Arjuna, one who, taking oneself as the measure, sees equally everywhere, whether in pleasure or in pain, is regarded as the highest yogi.",
    lesson: "The highest yogi is not the one who sits longest in meditation, but the one who feels another's joy and pain as their own. Empathy is the fruit of real spiritual practice. Treat others as you would wish to be treated, because at heart they are just like you.",
    reflection: "Whose pain or joy have you been too busy to notice?",
    action: "Ask one person today how they are really doing, and listen fully without fixing or advising.",
    themes: ["relationships", "service"],
  },
  {
    id: "6.35",
    chapter: 6,
    verse: 35,
    chapterName: "Dhyana Yoga",
    sanskrit: "असंशयं महाबाहो मनो दुर्निग्रहं चलम् ।\nअभ्यासेन तु कौन्तेय वैराग्येण च गृह्यते ॥६-३५॥",
    transliteration: "asaṃśayaṃ mahābāho mano durnigrahaṃ calam\nabhyāsena tu kaunteya vairāgyeṇa ca gṛhyate",
    meaning: "Without doubt, O mighty-armed one, the mind is restless and hard to restrain. But, O son of Kunti, it can be brought under control through practice (abhyasa) and detachment (vairagya).",
    lesson: "Krishna agrees with Arjuna that the mind is hard to manage, so struggling with it is normal, not a personal failure. The way forward has two parts: steady practice, and gradually letting go of what pulls you away. If restlessness or low mood stays heavy for a long time, speaking with a doctor or counsellor is also part of caring for your mind.",
    reflection: "What one practice could you repeat daily, and what one distraction could you loosen your grip on?",
    action: "Choose one tiny daily practice, such as two minutes of silence, a short prayer or a walk without your phone, and do it today.",
    themes: ["discipline"],
  },
  {
    id: "9.22",
    chapter: 9,
    verse: 22,
    chapterName: "Raja Vidya Raja Guhya Yoga",
    sanskrit: "अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते ।\nतेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम् ॥९-२२॥",
    transliteration: "ananyāścintayanto māṃ ye janāḥ paryupāsate\nteṣāṃ nityābhiyuktānāṃ yogakṣemaṃ vahāmyaham",
    meaning: "Those who worship Me with undivided devotion, thinking of no other, ever devoted to Me: for them I carry yoga-kshema, providing what they lack and preserving what they have.",
    lesson: "For devotees, this is a promise of care: you are not alone in carrying your life. Trust does not replace effort, and you still do your part with diligence, but it lifts the weight of anxiety from your shoulders. Devotion and responsibility walk together.",
    reflection: "What burden are you carrying alone that you could also offer in prayer?",
    action: "As a devotional practice, spend five minutes today in prayer or naam jap (repeating a divine name, such as \"Radhe Radhe\"), offering one specific worry.",
    themes: ["fear", "gratitude"],
  },
  {
    id: "9.26",
    chapter: 9,
    verse: 26,
    chapterName: "Raja Vidya Raja Guhya Yoga",
    sanskrit: "पत्रं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति ।\nतदहं भक्त्युपहृतमश्नामि प्रयतात्मनः ॥९-२६॥",
    transliteration: "patraṃ puṣpaṃ phalaṃ toyaṃ yo me bhaktyā prayacchati\ntadahaṃ bhaktyupahṛtamaśnāmi prayatātmanaḥ",
    meaning: "Whoever offers Me with devotion a leaf, a flower, a fruit or water, I accept and partake of that loving offering from one whose heart is pure.",
    lesson: "The Divine is not impressed by size or cost, only by love. A single flower given with a full heart means more than a grand gesture made for show. This makes devotion open to everyone, whatever their means.",
    reflection: "What simple thing could you offer today with your whole heart?",
    action: "As a devotional practice, offer a little water, a flower or a fruit at your prayer place today, or simply a moment of heartfelt thanks.",
    themes: ["gratitude", "service"],
  },
  {
    id: "12.13",
    chapter: 12,
    verse: 13,
    chapterName: "Bhakti Yoga",
    sanskrit: "अद्वेष्टा सर्वभूतानां मैत्रः करुण एव च ।\nनिर्ममो निरहङ्कारः समदुःखसुखः क्षमी ॥१२-१३॥",
    transliteration: "adveṣṭā sarvabhūtānāṃ maitraḥ karuṇa eva ca\nnirmamo nirahaṅkāraḥ samaduḥkhasukhaḥ kṣamī",
    meaning: "One who bears ill will toward no being, who is friendly and compassionate, free from possessiveness and ego, even-minded in pain and pleasure, and forgiving... (The description continues in the next verse, which concludes that such a devotee is dear to Krishna.)",
    lesson: "Krishna's portrait of the beloved devotee is a portrait of a good human being: friendly, kind, humble and forgiving. Devotion shows up as character, not only as ritual. Each quality here is something you can practise in your very next conversation.",
    reflection: "Which of these qualities, friendliness, compassion, humility or forgiveness, would most soften your life right now?",
    action: "Let go of one small grudge today: forgive silently, even if you say nothing.",
    themes: ["relationships", "anger", "ego"],
  },
  {
    id: "12.15",
    chapter: 12,
    verse: 15,
    chapterName: "Bhakti Yoga",
    sanskrit: "यस्मान्नोद्विजते लोको लोकान्नोद्विजते च यः ।\nहर्षामर्षभयोद्वेगैर्मुक्तो यः स च मे प्रियः ॥१२-१५॥",
    transliteration: "yasmānnodvijate loko lokānnodvijate ca yaḥ\nharṣāmarṣabhayodvegairmukto yaḥ sa ca me priyaḥ",
    meaning: "One by whom the world is not disturbed, and who is not disturbed by the world, who is free from elation, envy, fear and anxiety, is dear to Me.",
    lesson: "A peaceful person neither troubles others nor is easily troubled by them. This is not coldness but inner balance, and it makes us safe to be around. Peace given and peace kept are two sides of one practice.",
    reflection: "Do people feel calmer or more tense after spending time with you?",
    action: "In one conversation today, consciously lower your voice and slow your pace, and notice how the other person responds.",
    themes: ["relationships", "fear", "anger"],
  },
  {
    id: "16.1",
    chapter: 16,
    verse: 1,
    chapterName: "Daivasura Sampad Vibhaga Yoga",
    sanskrit: "अभयं सत्त्वसंशुद्धिर्ज्ञानयोगव्यवस्थितिः ।\nदानं दमश्च यज्ञश्च स्वाध्यायस्तप आर्जवम् ॥१६-१॥",
    transliteration: "abhayaṃ sattvasaṃśuddhirjñānayogavyavasthitiḥ\ndānaṃ damaśca yajñaśca svādhyāyastapa ārjavam",
    meaning: "Fearlessness, purity of heart, steadfastness in knowledge and yoga, charity, self-control, sacrifice (yajna), study of scripture, austerity (tapas) and straightforwardness... (The list of divine qualities continues in the next two verses.)",
    lesson: "Krishna begins his list of divine qualities with fearlessness, a calm courage rooted in trust and a pure heart. The rest of the list reads like a practical plan for character: give, restrain, study, simplify and be straight with people. Every one of these can be grown a little each day.",
    reflection: "Which divine quality in this verse would you most like to grow this month?",
    action: "Choose one quality from this verse and practise it deliberately once today, for example through an honest conversation or a small anonymous gift.",
    themes: ["fear", "discipline", "service"],
  },
  {
    id: "17.15",
    chapter: 17,
    verse: 15,
    chapterName: "Shraddhatraya Vibhaga Yoga",
    sanskrit: "अनुद्वेगकरं वाक्यं सत्यं प्रियहितं च यत् ।\nस्वाध्यायाभ्यसनं चैव वाङ्मयं तप उच्यते ॥१७-१५॥",
    transliteration: "anudvegakaraṃ vākyaṃ satyaṃ priyahitaṃ ca yat\nsvādhyāyābhyasanaṃ caiva vāṅmayaṃ tapa ucyate",
    meaning: "Speech that causes no distress, that is truthful, pleasant and beneficial, together with the regular recitation of sacred texts, is called austerity of speech.",
    lesson: "Clean speech is a daily spiritual discipline: true, kind, helpful and never meant to wound. The verse offers a simple filter before speaking: is it true, is it kind, is it useful? Regular recitation of sacred words trains the tongue toward gentleness.",
    reflection: "Did your words today pass the test of truthful, kind and helpful?",
    action: "For one whole conversation today, check each sentence before you say it: is it true, kind and helpful? If not, pause.",
    themes: ["relationships", "discipline"],
  },
  {
    id: "17.20",
    chapter: 17,
    verse: 20,
    chapterName: "Shraddhatraya Vibhaga Yoga",
    sanskrit: "दातव्यमिति यद्दानं दीयतेऽनुपकारिणे ।\nदेशे काले च पात्रे च तद्दानं सात्त्विकं स्मृतम् ॥१७-२०॥",
    transliteration: "dātavyamiti yaddānaṃ dīyate'nupakāriṇe\ndeśe kāle ca pātre ca taddānaṃ sāttvikaṃ smṛtam",
    meaning: "A gift given because giving is right, to one from whom nothing is expected in return, at the proper place and time and to a worthy recipient, is considered sattvic (of the nature of goodness).",
    lesson: "The purest giving expects nothing back, neither repayment nor praise. It is also thoughtful: the right help, at the right time, to the right person. Generosity offered this way enriches the giver as much as the receiver.",
    reflection: "When you give, are you quietly expecting something in return?",
    action: "Give something today, whether money, food, time or a skill, to someone who cannot repay you, and keep it private.",
    themes: ["money", "service", "gratitude"],
  },
  {
    id: "18.66",
    chapter: 18,
    verse: 66,
    chapterName: "Moksha Sannyasa Yoga",
    sanskrit: "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज ।\nअहं त्वा सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः ॥१८-६६॥",
    transliteration: "sarvadharmānparityajya māmekaṃ śaraṇaṃ vraja\nahaṃ tvā sarvapāpebhyo mokṣayiṣyāmi mā śucaḥ",
    meaning: "Setting aside all forms of dharma, take refuge in Me alone. I will free you from all sins; do not grieve.",
    lesson: "Commentators across traditions read this closing teaching in different ways, but all of them hear in it a call to take refuge wholeheartedly in the Divine. For a person living in the world, surrender does not mean dropping one's responsibilities; it means releasing the ego's anxious need to control everything. Its last words, \"do not grieve\", are among the most comforting in the Gita.",
    reflection: "What are you trying to control so tightly that it has become a burden?",
    action: "Tonight, before sleep, name one worry and consciously place it in the Divine's hands in a short prayer.",
    themes: ["fear", "ego"],
  },
  {
    id: "18.78",
    chapter: 18,
    verse: 78,
    chapterName: "Moksha Sannyasa Yoga",
    sanskrit: "यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः ।\nतत्र श्रीर्विजयो भूतिर्ध्रुवा नीतिर्मतिर्मम ॥१८-७८॥",
    transliteration: "yatra yogeśvaraḥ kṛṣṇo yatra pārtho dhanurdharaḥ\ntatra śrīrvijayo bhūtirdhruvā nītirmatirmama",
    meaning: "Wherever there is Krishna, the master of yoga, and wherever there is Arjuna, the archer, there, I am convinced, are fortune, victory, prosperity and steadfast righteousness. (Sanjaya's closing words of the Gita.)",
    lesson: "When wisdom (Krishna) and committed effort (Arjuna) work together, good fortune follows. Neither talent nor guidance is enough alone; they need each other. Invite higher guidance into your work, and then do your part with full commitment.",
    reflection: "In your current goal, what is missing: the guidance or the effort?",
    action: "Before your most important work today, take a moment for prayer or quiet reflection, then give it your best effort.",
    themes: ["leadership", "success-and-failure"],
  },
];

const BY_ID = new Map<string, GitaVerse>(GITA.map((v) => [v.id, v]));

/** Look up a verse by its "chapter.verse" id, e.g. gitaById("2.47"). */
export function gitaById(id: string): GitaVerse | undefined {
  return BY_ID.get(id.trim());
}
